// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJUtPQb9Fo8NxoI_1jwMm-8jM-kMyWAiM',
    appId: '1:287228447723:web:fe6a4fcf3641b8eca7a7ae',
    messagingSenderId: '287228447723',
    projectId: 'angime-24c71',
    authDomain: 'angime-24c71.firebaseapp.com',
    storageBucket: 'angime-24c71.appspot.com',
    measurementId: 'G-RT026JCZXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0hGJG6_pQ2C97NOZq_Fplx3I8B5xyZIo',
    appId: '1:287228447723:android:30607f54e971fe8da7a7ae',
    messagingSenderId: '287228447723',
    projectId: 'angime-24c71',
    storageBucket: 'angime-24c71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4llaD8y4HbD_JI_pczw7ttydNXz93XuM',
    appId: '1:287228447723:ios:a51b8aa6d86c8b72a7a7ae',
    messagingSenderId: '287228447723',
    projectId: 'angime-24c71',
    storageBucket: 'angime-24c71.appspot.com',
    iosClientId: '287228447723-3f5rcdm9rulqritbtkoev17laeijqvua.apps.googleusercontent.com',
    iosBundleId: 'com.example.angime',
  );
}
